### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta-hue-driver#6]
```js

/root/zetta/robotics-demo/node_modules/zetta-hue-driver/node_modules/node-hue-api/node_modules/q/q.js:126
                    throw e;
                          ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by AdamMagaluk** [comment]
Fixed in af7f8fe3dd7b5640c086ae851080d89e3e4d9213
